version: "2"
services:
  # NGINX Container
  drone1-nginx:
    build: 
      context: drone1-nginx/
      dockerfile: Dockerfile
    ports:                          
     - "8081:80"
  # NodeJS container
  drone1-nodejs:
    build:
      context: drone1-nodejs/
      dockerfile: Dockerfile
    ports:                           
     - '8082:3000'                
  # MongoDB container
  drone1-mongodb:
    build:
      context: drone1-mongodb/
      dockerfile: Dockerfile
    #ports:
    #  - '27017:27017'                
  drone1-mosquitto:
    build:
      context: drone1-mosquitto/
      dockerfile: Dockerfile
    ports:
     # - "1883:1883"
     # - "9001:9001" 
