version: "2"
services:
  # NGINX Container
  drone1-nginx:
    container_name: nginx
    build: 
      context: drone1-nginx/
      dockerfile: Dockerfile
    ports:                          
     - "8081:80"
  # MongoDB container
  drone1-mongodb:
    container_name: mongo
    image: mongo
    build: 
      context: drone1-mongodb/
      dockerfile: Dockerfile
    volumes:
     - ./data:/data/db
  # ports:
  #  - '27017:27017'   
  drone1-mosquitto:
    container_name: moquitto
    build:
      context: drone1-mosquitto/
      dockerfile: Dockerfile
    #ports:
     # - "1883:1883"
     # - "9001:9001" 
  # NodeJS container
  drone1-nodejs:
    container_name: node
    restart: always
    build: 
      context: drone1-nodejs/
      dockerfile: Dockerfile
    ports:                           
     - '8082:3000'     
    links:
     - drone1-mongodb   
     - drone1-mosquitto
  # Mockup container
  drone1-mockup:
    container_name: mockup
    restart: always
    build: 
      context: drone1-mockup/
      dockerfile: Dockerfile
    links:
     - drone1-mosquitto
